In [1]:
import numpy as np

print("NumPy", np.__version__, "listo para usar.")

NumPy 2.1.3 listo para usar.


In [3]:
import numpy as np
precios = np.array([143, 209, 212, 403])   # AMZN, NVDA, MSFT, V

print(precios)
print("shape:", precios.shape)
print("dtype:", precios.dtype)

[143 209 212 403]
shape: (4,)
dtype: int64


In [5]:
precios_5_dias = np.array([
    [143, 140, 141, 142, 144],   # AMZN
    [209, 211, 222, 240, 256],   # NVDA
])

print(precios_5_dias)
print("shape:", precios_5_dias.shape, "  # (2 activos, 5 días)")

[[143 140 141 142 144]
 [209 211 222 240 256]]
shape: (2, 5)   # (2 activos, 5 días)


In [9]:
cantidades = np.array([17, 8, 20, 10])   # 17, 8, 20, 10
rendimientos = np.array([8.33, -3.75, 8.82, 10.00]) # 8.33, -3.75, 8.82, 10.00

print(cantidades, cantidades.dtype)
print(rendimientos, rendimientos.dtype)

[17  8 20 10] int64
[ 8.33 -3.75  8.82 10.  ] float64


In [10]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [11]:
precios_actuales = np.array([195, 385, 185, 165])
precios_compra = np.array([180, 400, 170, 150])

valor_invertido = cantidades * precios_compra
valor_actual = cantidades * precios_actuales

print("Valor actual:", valor_actual)

Valor actual: [3315 3080 3700 1650]


**✏️ Completa el código** — calcula `ganancia` y `en_perdida` (verdadero/falso).

In [14]:
ganancia = valor_actual - valor_invertido
en_perdida = ganancia < 0

print("Ganancia:", ganancia)
print("En pérdida:", en_perdida)

Ganancia: [ 255 -120  300  150]
En pérdida: [False  True False False]


In [15]:
AMZN = np.array([0.012, 0.008, -0.004, 0.015, 0.006, -0.002, 0.010, 0.003])

print("Número de días:", len(AMZN))
print("Primer día:", AMZN[0])
print("Último día:", AMZN[-1])

Número de días: 8
Primer día: 0.012
Último día: 0.003


In [16]:
promedio_aapl = AMZN.mean()
peor_dia = AMZN.min()

print("Promedio:", promedio_aapl)
print("Peor día:", peor_dia)

Promedio: 0.006
Peor día: -0.004


In [18]:
riesgo_aapl = AMZN.std()
print("Riesgo (std):", riesgo_aapl)

Riesgo (std): 0.006224949798994366


In [19]:
AMZN = np.array([0.012, 0.008, -0.004, 0.015, 0.006, -0.002, 0.010, 0.003])
NVDA = np.array([0.004, 0.003, 0.005, 0.002, 0.006, 0.004, 0.003, 0.005])
MSFT = np.array([-0.010, -0.015, 0.002, -0.008, -0.012, 0.005, -0.020, -0.006])
V = np.array([0.030, -0.025, 0.040, 0.015, -0.020, 0.035, -0.010, 0.020])

In [23]:
activos = {"AMZN": AMZN, "NVDA": NVDA, "MSFT": MSFT, "V": V}

for nombre, serie in activos.items():
    promedio = serie.mean()
    riesgo = serie.std()
    print(f"{nombre}: rendimiento {promedio:.4f}  |  riesgo {riesgo:.4f}")

AMZN: rendimiento 0.0060  |  riesgo 0.0062
NVDA: rendimiento 0.0040  |  riesgo 0.0012
MSFT: rendimiento -0.0080  |  riesgo 0.0078
V: rendimiento 0.0106  |  riesgo 0.0239


In [24]:
pesos = np.array([0.35, 0.40, 0.10, 0.15])  # AMNZ, NVDA, MSFT, V — suman 1.0

rendimiento_portafolio = AMZN*pesos[0] + NVDA*pesos[1] + MSFT*pesos[2] + V*pesos[3]
print(rendimiento_portafolio)

[ 0.0093  -0.00125  0.0068   0.0075   0.0003   0.00665  0.0012   0.00545]


In [26]:
rendimiento_promedio_portafolio = rendimiento_portafolio.mean()
riesgo_portafolio = rendimiento_portafolio.std()

print(f"Rendimiento promedio del portafolio: {rendimiento_promedio_portafolio:.4f}")
print(f"Riesgo del portafolio: {riesgo_portafolio:.4f}")

Rendimiento promedio del portafolio: 0.0045
Riesgo del portafolio: 0.0036


In [27]:
riesgos_individuales = np.array([AMZN.std(), NVDA.std(), MSFT.std(), V.std()])
riesgo_promedio_simple = (riesgos_individuales * pesos).sum()

print(f"Riesgo si solo promediaras los riesgos individuales: {riesgo_promedio_simple:.4f}")
print(f"Riesgo real del portafolio combinado: {riesgo_portafolio:.4f}")

Riesgo si solo promediaras los riesgos individuales: 0.0070
Riesgo real del portafolio combinado: 0.0036


In [28]:
mis_pesos = np.array([0.25, 0.25, 0.25, 0.25])  # cambia estos números — deben sumar 1.0

mi_portafolio = AMZN*mis_pesos[0] + NVDA*mis_pesos[1] + MSFT*mis_pesos[2] + V*mis_pesos[3]
print(f"Rendimiento: {mi_portafolio.mean():.4f}  |  Riesgo: {mi_portafolio.std():.4f}")

Rendimiento: 0.0032  |  Riesgo: 0.0070
